# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('image_path', models.CharField(max_length=200)),
                ('pdf_path', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloads', models.IntegerField(default=0)),
            ],
        ),
    ]
