# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tale',
            old_name='pdf_path',
            new_name='doc_path',
        ),
        migrations.AlterField(
            model_name='tale',
            name='about',
            field=models.TextField(max_length=1000),
        ),
    ]
