# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0003_taletag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taletag',
            name='help',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='taletag',
            name='label',
            field=models.CharField(default='', max_length=300),
        ),
    ]
